services:
  #server layer
  fast-api:
    depends_on:
      - db
    
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app

    working_dir: /app
    command: uvicorn server:app --host 0.0.0.0 --reload
    ports:
      - 8000:8000

    environment:
      PG_HOST: db

  streamlit:
  #visual presentation layer
    depends_on:
      - fast-api
      - db

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app

    working_dir: /app
    command: streamlit run Welcome.py --server.enableCORS false --server.enableXsrfProtection false --server.fileWatcherType poll
    ports:
      - 8501:8501

    environment:
      FAST_API_HOST: fast-api

  db:
  #database layer
    image: postgres:latest

    restart: unless-stopped
    
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    
    environment:
      POSTGRES_USER: ibcm
      POSTGRES_DB: ibcm
      POSTGRES_PASSWORD: password
    
    ports:
      - 5432:5432

volumes:
  postgres-data:
