version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ib-college-match
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
